[pytest]
testpaths = tests/
addopts = --alluredir=allure-results
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    P0: Critical priority tests
    P1: High priority tests
    P2: Medium priority tests
    P3: Low priority tests